#APACHE
server:
  port: ${PORT:8080}

spring:
  application:
      name: sidecar-node

sidecar:
  port: 3000
  home-page-uri: http://localhost:${sidecar.port}/welcome
  health-uri: http://localhost:${sidecar.port}/health